name: fruit_scanner
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.2
  image: ^4.5.4
  flutter_xlider: ^3.5.0
  video_player: ^2.10.0
  ultralytics_yolo: ^0.1.28
  path_provider: ^2.1.5
  # tflite_flutter: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/models/best_nano_float32.tflite
    - assets/models/labels.txt
